name: ci-Gitea Actions Demo

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: chekout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          target: build
          push: true
          context: .
          platforms: linux/amd64
          tags: |
           ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
    
      - name: Run Trivy vulnerability scan
        run: |
             mkdir -p trivy-reports
             docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
             -v $(pwd)/trivy-reports:/report \
             aquasec/trivy:latest image \
             --no-progress \
             --ignore-unfixed \
             --severity CRITICAL,HIGH \
             --format template --template "@contrib/html.tpl" -o /report/trivy-report.html \
             ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}

      - name: Vérification du fichier Trivy
        run: ls -l ./trivy-reports
   
      - name: upload trivy report to s3
        uses:  jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --exclude "*" --include "trivy-report.html"
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: "./trivy-reports"
          DEST_DIR: "trivy-reports/"